### ISSUE TITLE
Deep learning Examples roadmap

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lance-deeplearning-recipes#5]
One end-to-end example for each of:
 - [x] LLM pre-training dataset creation and training
 - [x] Detection/segmentation Dataset creation and training
 - [x] Multi-modal dataset creation and training
 - [x] Compare system utilization, time per epoch etc.
 - [x] Parallelised dataset creation, updation, versioning, filtering on the fly while training examples.
 
Notebook tutorials:
- [x] EDA with lance datasets. Cover dataset lifecycle - creation, updation. Show ingesting various data types

**Comment by tanaymeh** [comment]
Let's make individual tickets for them and take them one by one.

**Comment by AyushExel** [comment]
Sounds good
